### ISSUE TITLE
Jens Modell to RainbowModel Software Architecture, Performance Test

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#1]
- LeaveOneOut
- More epochs
- less sensors

In order to do the LeaveOneOut tests, it makes sense to bring Jens Model in our own software architecture
Before: Get the same performance on the sensor subset (ca 88% accuracy) without LeaveOneOut

- windowize creates much more windows in our version -> compare

- where are the window differences (in the beginning of each activity) time dependency
- same labeling?

**Comment by lucasliebe** [comment]
i think this issue is already processed and probably even already merged so it will be closed
