### ISSUE TITLE
Window Analysis

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#10]
We are working with a black box model more or less. If the accuracy is not how we wish there are a lot of points in the process that could be responsible for that. The most important one is data quality. We know that we have a lot of wrong labeling, null activities, that accidentally include stuff that should be labeled as activity, wrong time periods, weird sensor positions and so on. 

In the end we can have a look on windows that were classified wrong by our model. If we now know how in theory a window must look like, that has the label "washing", than we can find patterns in the data, right and wrong classified.
- has the classified window the wrong label and was therefore predicted wrong?
- is it maybe not possible to predict a higher level activity with a window of that size, because its too similar to another label?
With these information we could decide to cut a timespan from the beginning and the end of an activity. We could see that a specific activity requires bigger windows, so the model can predict it. We could see that a specific activity is impossible to predict and run an algo that turns it into null and so on.

Create functions that take Windows and print/ save stats/visualization that bring us closer to answering these questions.
- idea: could we do a clustering with our windows to see what windows are similar to each other?
- must include: understanding how a window of a specific label roughly looks like in the visualization (you are the model that can predict?)

**Comment by lucasliebe** [comment]
will not be worked on because of time constraints
