### ISSUE TITLE
MulitOrhan

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#12]
Dont work on that before its not clear, that our normal single-window-based model doesnt get a good performance.

At the moment we windowize our data and predict single windows one at a time. Intuitively it makes sense for higher level activities to consider multiple windows, remember context to get a good prediction. What about LSTMs? We have a very random implementation (MultiOrhan) in ml-rainbow. It was never really tested on higher level activity prediction. Maybe also come up with a new model from a paper/ an existing implementation.
- refactor the pipeline, so you have an experiment that tests MulitOrhans performance
- develop analysis functions that show the improvement compare to our normal approach

**Comment by lucasliebe** [comment]
partially done and doesn`t need further work
