### ISSUE TITLE
Improve Multiprocessing

### ISSUE THREAD

**Issue by FranzSw** [Sensors-in-Paradise/UnicornML#13]
## Description

To speed up the processing of large data batches, we should encourage usage of multiprocessing. And example can be found in OpportunityML load_dataset 

Currently to make it work, the settings also have to be initialized in the main python file which gets executed, because the variables are not persisted over different threads. 

One solution could be to make the experiment-file detect if it is run in a parallel setting and exit / skip after initializing the settings, another one would be to pass all necessary settings to the multiprocessor function. The last I can think of to make the settings globally available without function call.

## Must Include

- [x] Find places where multiprocessing speeds up processing
- [x] Explore different solutions to described challenge (and upcoming ones) / decide on an approach
- [ ] Let the others know

**Comment by lucasliebe** [comment]
I think this is mostly done by now and will be closed for a better overview
