### ISSUE TITLE
Preprocessing Executable

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#24]
#11 wants to do the python pandas preprocessing live on the phone.
We found out, that creating custom preprocessing layers is complicated, as you need to do the preprocessing on tensors, not on numpy arrays or dataframes. The whole idea behind the layer was to export our python pandas preprocessing blackbox in another environment (Kotlin). @leandermasopust found a SDK that can maybe do just that. Lets find out!
Our export does not need to be .tflite. It could be anything, as long as the blackbox works

**Comment by leandermasopust** [comment]
https://chaquo.com/chaquopy/

**Comment by FranzSw** [comment]
The native tensorflow version from chaquo is 2.1, we are currently using 2.7. 

I think you can still install a newer version with pip, but it might not reach the same speed as with the native one.

Src: https://github.com/chaquo/chaquopy/issues/374

**Comment by lucasliebe** [comment]
this will be closed because of time constraints

**Comment by mhsmith** [comment]
FYI: Chaquopy also supports TensorFlow Lite version 2.5, which might be more compatible with your model. See https://github.com/chaquo/chaquopy/issues/675.
