### ISSUE TITLE
Recording Filter functions

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#3]
Our own nursing HAR dataset might have some problems if we want to predict labels of it directly. There are
- activities that consist of multiple other activities,
- activities that are to small/ short

We need to relabel stuff, we need to summarize small labels to scenario labels, we need to filter out activities, split recordings.
We skip first recordings of new recorders, have a 3 sec transition time (labeling problem not fast enough, only take the core) and so on.

In the end we want to try to train the model on different label sets, on different data subsets to get the most useful, working prediction model from our data.

I suggest we write some functions that take and return recordings (datatype) and that fullfill the tasks mentioned above

**Comment by kpostnov** [comment]
Implemented in ml-rainbow repository. PR ready for review.

**Comment by lucasliebe** [comment]
this should be closed after the code is transferred to this repository later on
