### ISSUE TITLE
Cache Preprocessing Progress

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#5]
We work with very much data and our csv-reading, interpolation, normalization, filter/ relabeling functions take some time to execute. We dont want to execute all these functions for every model training, therefore we want to save the processed data. Working with our internal datatype "Recording" (with a dataframe) we would like to have the functions
- save_recordings(path)
- load_recordings(path)

PS: Maybe its a good idea to also have save_windows(path), load_windows(path), one processing step later

**Comment by kpostnov** [comment]
Implemented in ml-rainbow repository. PR ready for review.

**Comment by lucasliebe** [comment]
this should be closed after the code is transferred to this repository later on
