### ISSUE TITLE
Deep Learning Model Analysis

### ISSUE THREAD

**Issue by valentindoering** [Sensors-in-Paradise/UnicornML#8]
If the model doesnt work, we can build different test setups, which takes some time and not always gives us a good solution.
The Online-Tool Weights & Biases gives you interesting insides in the training process of your model training. If we use this tool we can probably get a much better understanding, why certain parameters in the system work with our models and why not.

- an example model training with Weights and Biases is already implemented in ml-rainbow

Todo:
- ask me (Valentin) to get invited to our Weights and Biases account
- create a new experiment where you do a simple model training with Weights and Biases
- understand the stats that we get from the online tool
- present Weights and Biases to the group, what insides did you gather?

**Comment by lucasliebe** [comment]
might be done in some bachelor thesis but is out of scope of the project for us
